### ISSUE TITLE
readwirte権限を持ったmongoユーザにてmongooseにてcollectionがないとデータを追加できない

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/docker_mongo#5]
(node:5500) UnhandledPromiseRejectionWarning: MongooseError: Operation `somemodels.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/kazune/work/python/docker_mongo/src/project/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:184:20)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by kmchord9** [comment]
予めmongodbにcollectionを作成しておく必要があり
